config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('soju.urls')),
    path('search/', include('survey.urls')),

]

soju/urls.py
from django.urls import path

from .views import *

app_name = 'soju'

urlpatterns = [
    path('', home_url, name='home_url'),
    path('reco/', reco_url, name='reco'),
    path('<beer_name>/', beerDetail, name='beerDetail'),

]

survey/urls.py
from django.urls import path

from .views import *

app_name = 'survey'

urlpatterns = [
    path('/', beer_list, name='beer_list'),
    path('result/', search, name='search'),


]

soju/models.py
from django.db import models
from django.urls import reverse


class Beer(models.Model):
    # 주종
    category = models.CharField(max_length=20, db_index=True, null=True)
    # 제품 이름
    name = models.CharField(max_length=200, db_index=True, null=True)
    # 사진
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    # 설명
    description = models.TextField(blank=True)
    # 간단한 설명
    meta_description = models.CharField(max_length=40, null=True, blank=True)
    # 도수를 소수점으로 나타낸다. 10의자리까지 소수아래 한자리까지만
    ABV = models.DecimalField(max_digits=6, decimal_places=1, blank=True)
    # 당도를 숫자로 나타낸다. 양의 정수만 가능함
    sugar = models.PositiveIntegerField(blank=True)
    # 산미
    sanmi = models.PositiveIntegerField(blank=True)
    # 향
    s = models.CharField(max_length=20, null=True, blank=True)

    # # 링크
    # link = models.TextField(blank=True)
    # # 별점
    # star = models.IntegerField(null=True, blank=True)
    # # 좋아요
    # like = models.IntegerField(null=True, blank=True)

    # # 리뷰
    # re = models.CharField(max_length=40, null=True, blank=True)

    class Meta:
        ordering = ['category']  # 이름으로 정렬

    def __str__(self):
        return self.name

    # url 넘겨줄 때 views.py 의 beer_detail 이용하고 id와 slug 를 넘겨준다.
    def get_absolute_url(self):
        return reverse('soju:beerDetail', args=[self.name])


# class User(models.Model):
#     user_name = models.CharField(max_length=10, db_index=True)
#     password = models.CharField(max_length=64, verbose_name='Password')
#     registered = models.DateTimeField(auto_now_add=True, verbose_name='AddDate')
#
#     def __self__(self):
#         return self.username
#
#     class Meta:
#         db_table = 'user'
#         verbose_name = 'user'
#         verbose_name_plural = 'user'


# class Like(models.Model):
#     user_name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
#     user_like = models.ForeignKey(Beer, on_delete=models.SET_NULL, null=True, related_name='beer')


# class Userstar(models.Model):
#     name = models.ForeignKey(User, on_delete=models.CASCADE, related_name='name', null=True)
#     category = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_category', null=True)
#     # 제품 이름
#     name = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_name', null=True)
#     # 도수를 소수점으로 나타낸다. 10의자리까지 소수아래 한자리까지만
#     ABV = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_ABV', null=True)
#     # 당도를 숫자로 나타낸다. 양의 정수만 가능함
#     sugar = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_sugar', null=True)
#     # 별점
#     star = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_star', null=True)
#     # 산미
#     sanmi = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_sanmi', null=True)
#     # 향
#     s = models.ForeignKey(Beer, on_delete=models.SET_NULL, related_name='star_s', null=True)

soju/views.py
from django.shortcuts import render, get_object_or_404
from .models import *


def home_url(request):
    beers = Beer.objects.all()
    return render(request, 'soju/index.html', {'beers':beers})


def beerDetail(request, beer_name=None):
    beer = get_object_or_404(Beer, name=beer_name)
    return render(request, 'soju/detail.html', {'beer':beer})


def reco_url(request):
    return render(request, 'soju/recommend.html')

survey/views.py
from django.shortcuts import render
from soju.models import *
from django.db.models.query_utils import Q


def search(request):
    beers = Beer.objects.all()
    query1 = Q()
    query2 = Q()
    query3 = Q()
    a = request.GET.getlist('category')
    b = request.GET.getlist('sanmi')
    c = request.GET.getlist('sugar')
    d = request.GET.get('ABV1')
    e = request.GET.get('ABV2')
    if a:
        for i in a:
            query1 = query1 | Q(category=i)

        beers = beers.filter(query1)
    if b:
        for i in b:
            query2 = query2 | Q(sanmi=i)

        beers = beers.filter(query2)
    if c:
        for i in c:
            query3 = query3 | Q(sugar=i)

        beers = beers.filter(query3)
    if d and e:
        beers = beers.filter(ABV__range=(d, e))

    return render(request, 'survey/result.html', {'beers': beers})


def beer_list(request):
    return render(request, 'survey/survey.html')

soju/templates/soju/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <title>LEWIS</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link href="{% static 'css/main2.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <header class="header header-js">
      <div class="header__wrapper header-wrapper-js">
        <div class="header__left-inner">
          <div class="header__logo-wrapper">
            <div class="header__logo"><a href="/">Hel<i>p<span>m</span>e</i>e</a></div>
          </div><a class="header__author-mail" href="#"></a>
        </div>
        <div class="header__right-inner">
          <ul class="header__social">
              <li class="header__social-item"><a class="header__social-link" href="{% url 'survey:beer_list' %}">제품검색</a></li>
<!--              <li class="header__social-item"><a class="header__social-link" href="{% url 'soju:reco' %}">제품목록</a></li>-->

          </ul>
          <div class="header__burger"><span></span></div>
          <div class="header__menu">
            <div class="header__menu-exit"></div>
            <ul class="header__menu-social">
            </ul>
            <div class="header__menu-content">
              <ul class="header__menu-list">
                 <li class="header__menu-item" data-menuanchor="cases"><a class="header__menu-link" href="{% url 'survey:beer_list' %}">제품검색</a></li>
<!--                  <li class="header__menu-item" data-menuanchor="cases"><a class="header__menu-link" href="{% url 'soju:reco' %}">제품목록</a></li>-->

              </ul>
              <ul class="header__menu-contacts">
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>

    <main class="main">

        <!-- Post-->
        <div class="blog">
          <div class="container-fluid">
            <div class="blog__inner">
              <h2 class="blog__title"></h2>
              <div class="line blog__line"></div>
              <div>
                <p class="blog__text"></p>
                <p style="font-size: 60px">{{beer.name}}</p>

                <hr>
                <div class="row">
                  <div class="col-md-6">

                    <img src={{beer.image.url}} alt="" width="100%" height="auto">
                  </div>
                  <!-- Developer skills-->
                  <div class="col-md-6">
                    <!-- Skill-->
                    <div>
                      <div class="services__skill-header">
                        <div class="services__skill-title">ABV</div>
                        <div class="services__skill-percent">{{beer.ABV}}</div>
                      </div>
                      <div class="services__skill-progress">
                        <div class="services__skill-gold-line" style="width:{{beer.ABV}}%"></div>
                        <div class="services__skill-white-line" style="width:100%"></div>
                      </div>
                    </div>
                    <!-- Skill-->
                    <div class="services__skill">
                      <div class="services__skill-header">
                        <div class="services__skill-title">SUGAR</div>
                        <div class="services__skill-percent">{{beer.sugar}}</div>
                      </div>
                      <div class="services__skill-progress">
                        <div class="services__skill-gold-line" style="width:{{beer.sugar}}%"></div>
                        <div class="services__skill-white-line" style="width:100%"></div>
                      </div>
                    </div>
                    <!-- Skill-->
                    <div class="services__skill">
                      <div class="services__skill-header">
                        <div class="services__skill-title">Malty</div>
                        <div class="services__skill-percent">{{beer.sanmi}}</div>
                      </div>
                      <div class="services__skill-progress">
                        <div class="services__skill-gold-line" style="width:{{beer.sanmi}}%"></div>
                        <div class="services__skill-white-line" style="width:100%"></div>
                      </div>
                    </div>
                    <!-- Skill-->
                    <div class="services__skill">
                      <div class="services__skill-header">
                        <div class="services__skill-title">INCENSE</div>
                        <div class="services__skill-percent">{{beer.s}}</div>
                      </div>
                      <div class="services__skill-progress">
                        <div class="services__skill-gold-line" style="width:{{beer.s}}%"></div>
                        <div class="services__skill-white-line" style="width:100%"></div>
                      </div>
                    </div>
                  </div>
                </div>
                <p class="blog__text--big blog__text--big--mt-70">{{beer.metadescription}}</p>
                <p class="blog__text blog__text--mt-120">{{beer.description}}</p>
                <p class="blog__text"></p>
                <div class="blog__img-wrap"><input type="button" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true" value="뒤로가기" onclick="history.back(-1);"> </div>
                <!-- Author of the post info-->
                <div class="blog-more blog__more">
                  <div class="blog-more__author"> <span class="blog-more__author-text">SJ company</span><span class="blog-more__author-name">Product by : 살려조</span></div>
                </div>
              </div>
              <div class="line blog__line blog__line--mt-70"></div>
          </div>
        </div>
      </div>
    </main>
    <script src="{% static 'js/libs.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

soju/templates/soju/index.html
{% extends 'base.html' %}
{% block detail %}

<!-- Cases section-->
        <div class="section section-cases pp-scrollable">
          <canvas class="noise"></canvas>
          <div class="section-main cases js-section" id="cases">
            <div class="cases__play-animation-right"></div>
            <div class="cases__play-animation-left"></div>
            <div class="cases__container">
              <div class="cases__row-wrapper">
                <div class="cases__row js-cases-row" >
                  <!-- Case card-->
                  {% for b in beers %}
                    <a class="cases__card js-cases-card" href="{{b.get_absolute_url}}">
                    <div class="cases__text">

                    </div><img class="cases__card-img" src="{{ b.image.url }}" alt="img" >
                    </a>
                  {% endfor %}

                </div>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

soju/templates/soju/recommend.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <title>LEWIS</title>
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link href="{% static 'css/main2.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main2.css' %}">
  </head>
  <body>
    <header class="header header-js">
      <div class="header__wrapper header-wrapper-js">
        <div class="header__left-inner">
          <div class="header__logo-wrapper">
            <div class="header__logo">Lew<i>i<span>i</span>i</i>s</div>
          </div><a class="header__author-mail" href="#">hello@georgelewis.com</a>
        </div>
        <div class="header__right-inner">
          <ul class="header__social">
            <li class="header__social-item"><a class="header__social-link" href="#">Behance</a></li>
            <li class="header__social-item"><a class="header__social-link" href="#">Instagram</a></li>
          </ul>
          <div class="header__burger"><span></span></div>
          <div class="header__menu">
            <div class="header__menu-exit"></div>
            <ul class="header__menu-social">
              <li class="header__social-item"><a class="header__social-link" href="#">Behance</a></li>
              <li class="header__social-item"><a class="header__social-link" href="#">Instagram</a></li>
            </ul>
            <div class="header__menu-content">
              <ul class="header__menu-list">
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#home">Home</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#cases">Portfolio</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#about">About</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#services">Services</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#partners">Testimonials</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#awards">Blog</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#testimonials">Clients</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#blog">Awards</a></li>
                <li class="header__menu-item"><a class="header__menu-link" href="index.html#contacts">Contacts </a></li>
              </ul>
              <ul class="header__menu-contacts">
                <li class="header__menu-contact"><a class="header__menu-link" href="#">+ 34 2454 3459 21</a></li>
                <li class="header__menu-contact"><a class="header__menu-link" href="#">hello@georgelewis.com</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>
    <main class="main">
      <!-- Main image of the case page-->
      <div class="head">
        {% static 'favicon/favicon-16x16.png' %}"
        <img class="head_img" src="{% static 'img/case/case-main-img.jpg' %}">
        <div class="head_text">
          <h1>둘러보기</h1>
        </div>
      </div>
<!--      헤드 고정 시켜볼까??   -->
      <div class="case-bg">
        <section class="content">
        {% for b in beers %}
          <a class="box-wrapper" href="{{b.get_absolute_url}}">
            <div class="a_box">
              <img class="photo" src="{{ b.image.url }}" >
                <div class="pop_up">
                 <h3 class="a_name">{{b.name}}</h3>
                  <p class="meta_description">{{b.meta_description}}</p>
                </div>
            </div>

          </a>
        {% endfor %}
        </section>
      </div>
    </main>
    <script src="{% static 'js/libs.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

survey/templates/survey/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <h1 style="text-align: center; color:white">결과</h1>
<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  <a href="/" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Home</a>
    <input type="button" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true" value="뒤로가기" onclick="history.back(-1);">
</div>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<style>
    body{
        background-color: #6B747D;

    }

</style>
<body>


    <div class ="container"> <!--여백추가 mt-5-->
        <div class="col-md-6">
        {% for beer in beers %}
        <div class="card text-white bg-secondary mb-3" style="width: 18rem;">

  <img src="{{ beer.image.url }}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">{{ beer.name }}</h5>
    <p class="card-text">{{ beer.meta_description }}</p>
      <a href="{{beer.get_absolute_url}}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">상세보기</a>
  </div>
</div>
        {% endfor %}
            </div>
    </div>
</div>
</div>
            </div>

    </div>
</body>
</html>

survey/templates/survey/survey.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<style>
    body{
        background-color: #6B747D;
        color:white;
    }

</style>
<body>

    <div class ="container">
        <div class= "row mt-5"> <!--여백추가 mt-5-->
            <div class= "col-12 text-center">

            </div>
        </div>
        <div class= "row">
            <div class= "col-12">
                <form class="form-inline my-2 my-md-0" method="get" action="{% url 'survey:search' %}">

                    <div class="form-group mb-3 mt-5">

                        <p>1. 종류 선택</p>
                        <label><input type="checkbox" name="category" value="흑맥주">흑맥주</label>
                        <label><input type="checkbox" name="category" value="밀맥주">밀맥주</label>
                        <label><input type="checkbox" name="category" value="과일맥주">과일맥주</label>
                        <label><input type="checkbox" name="category" value="수제맥주">수제맥주</label>
                    </div>
                    <div class="form-group mb-3 mt-5">
                        <p>2. 도수 입력</p>
                        <input type="number" class="form-control form-control-sm" id="ABV1" placeholder="최저도수" name="ABV1">
                        <input type="number" class="form-control form-control-sm" id="ABV2" placeholder="최고도수" name="ABV2">
                    </div>

                    <div class="form-group mb-3 mt-5">
                        <P>3. 산미 선택</P>
                        <label><input type="checkbox" name="sanmi" value=1> 1</label>
                        <label><input type="checkbox" name="sanmi" value=2> 2</label>
                        <label><input type="checkbox" name="sanmi" value=3> 3</label>
                        <label><input type="checkbox" name="sanmi" value=4> 4</label>
                        <label><input type="checkbox" name="sanmi" value=5> 5</label>
                        <label><input type="checkbox" name="sanmi" value=6> 6</label>
                        <label><input type="checkbox" name="sanmi" value=7> 7</label>
                        <label><input type="checkbox" name="sanmi" value=8> 8</label>
                        <label><input type="checkbox" name="sanmi" value=9> 9</label>
                        <label><input type="checkbox" name="sanmi" value=10> 10</label>
                    </div>
                        <p>4. 당도를 선택하세요</p>
                        <label><input type="checkbox" name="sugar" value=1> 1</label>
                        <label><input type="checkbox" name="sugar" value=2> 2</label>
                        <label><input type="checkbox" name="sugar" value=3> 3</label>
                        <label><input type="checkbox" name="sugar" value=4> 4</label>
                        <label><input type="checkbox" name="sugar" value=5> 5</label>
                        <label><input type="checkbox" name="sugar" value=6> 6</label>
                        <label><input type="checkbox" name="sugar" value=7> 7</label>
                        <label><input type="checkbox" name="sugar" value=8> 8</label>
                        <label><input type="checkbox" name="sugar" value=9> 9</label>
                        <label><input type="checkbox" name="sugar" value=10> 10</label>


                    <input class="btn btn-secondary btn-lg" type="submit" value="Submit">
                    <input class="btn btn-secondary btn-lg" type="reset" value="Reset">
                    <a href="/" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Home</a>

                </form>

            </div>
        </div>
    </div>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <title>BEER</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <meta name="theme-color" content="#ffffff">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/main2.css' %}" rel="stylesheet">
  </head>
  <body>
      <header class="header">
        <div class="header__wrapper">
          <div class="header__left-inner">
            <div class="header__logo-wrapper">
              <div class="header__logo"><a href="/">Hel<i>p<span>m</span>e</i>e</a></div>
            </div><a class="header__author-mail" href="#"></a>
          </div>
          <div class="header__right-inner">
            <ul class="header__social">
              <li class="header__social-item"><a class="header__social-link" href="{% url 'survey:beer_list' %}">제품검색</a></li>
<!--              <li class="header__social-item"><a class="header__social-link" href="{% url 'soju:reco' %}">제품목록</a></li>-->
            </ul>
            <div class="header__burger"><span></span></div>
            <div class="header__menu">
              <div class="header__menu-exit"></div>
              <div class="header__menu-content">
                <ul class="header__menu-list" id="myMenu">
                <!--큰거-->
                  <li class="header__menu-item" data-menuanchor="cases"><a class="header__menu-link" href="{% url 'survey:beer_list' %}">제품검색</a></li>
<!--                  <li class="header__menu-item" data-menuanchor="cases"><a class="header__menu-link" href="{% url 'soju:reco' %}">제품목록</a></li>-->
                </ul>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div id="pagepiling">
        {% block detail %}


        {% endblock %}
      </div>
    <script src="{% static 'js/libs.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>